import RootLayout from "@/components/Layouts/RootLayout";
import Banner from "@/components/UI/Banner";
import AllPc from "@/components/UI/AllPc";

import { useGetAllPcQuery } from "@/redux/api/api";
import Head from "next/head";
import React from "react";

const HomePage = () => {
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>;
  const { data } = useGetAllPcQuery();
  console.log(data);

  return (
    <div>
      <Banner></Banner>
      <AllPc allPc={data}></AllPc>
    </div>
  );
};

export default HomePage;
HomePage.getLayout = function getLayout(page) {
  return <RootLayout>{page}</RootLayout>;
};
